routes/web.php
    Route::get('/add_ride_inspection_lists/{ride_id}', 'Admin\RideInspectionListController@add_ride_inspection_lists')->name('addRideInspectionLists');
    Route::get('/cheack_ride_inspection_lists/', 'Admin\RideInspectionListController@cheackRideInspectionList')->name('cheackRideInspectionList');
    Route::get('/edit_ride_inspection_lists/{ride_id}', 'Admin\RideInspectionListController@edit_ride_inspection_lists')->name('editRideInspectionLists');
    Route::post('/update_ride_inspection_lists/{ride_id}', 'Admin\RideInspectionListController@update_ride_inspection_lists')->name('updatRideInspectionLists');

    Route::resource('zone_inspection_lists', 'Admin\ZoneInspectionListController');
    Route::get('/add_zone_inspection_lists/{zone_id}', 'Admin\ZoneInspectionListController@add_zone_inspection_lists')->name('addZoneInspectionLists');
    Route::get('/cheack_zone_inspection_lists/', 'Admin\ZoneInspectionListController@cheackzoneInspectionList')->name('cheackZoneInspectionList');
    Route::get('/edit_zone_inspection_lists/{zone_id}', 'Admin\ZoneInspectionListController@edit_zone_inspection_lists')->name('editZoneInspectionLists');
    Route::post('/update_zone_inspection_lists/{zone_id}', 'Admin\ZoneInspectionListController@update_zone_inspection_lists')->name('updatZoneInspectionLists');

    Route::resource('complaints', 'Admin\CustomerComplaintController');//done
    Route::resource('customer_feedbacks', 'Admin\CustomerFeedbackController');//done
    Route::resource('feedback_sub_category', 'Admin\FeedbackSubCategoryController');
    Route::get('/search_customer_feedbacks/', 'Admin\CustomerFeedbackController@search')->name('searchCustomerFeedBack');
    Route::post('get-feedback-sub-categories', 'Admin\GeneralController@getFeedbackSubCategories')->name('getFeedbackSubCategories');

    Route::get('get-park-zones', 'Admin\GeneralController@getParkZones')->name('getParkZones');
    Route::post('get-sub-stoppages-categories', 'Admin\GeneralController@getSubStoppageCategories')->name('getSubStoppageCategories');
    Route::get('get_park_rides', 'Admin\GeneralController@getParkRides')->name('getParkRides');
    Route::get('get-zone-rides', 'Admin\GeneralController@getZonerides')->name('getZonerides');
    Route::get('getHasSkillgame', 'Admin\GeneralController@getHasSkillgame')->name('getHasSkillgame');
    Route::get('getSupervisorByPark', 'Admin\GeneralController@getSupervisorByPark')->name('getSupervisorByPark');
    Route::get('getOperatorByPark', 'Admin\GeneralController@getOperatorByPark')->name('getOperatorByPark');
    Route::get('get-training-checklists', 'Admin\GeneralController@getTrainingChecklists')->name('getTrainingChecklists');
    Route::get('get-users-by-type', 'Admin\GeneralController@getUsersByType')->name('getUsersByType');
    Route::get('get-list-type', 'Admin\GeneralController@getListType')->name('getListType');
    Route::get('get-checklist-type', 'Admin\GeneralController@getChecklistType')->name('getChecklistType');


    Route::resource('rsr_reports', 'Admin\RsrReportController');//done
    Route::get('rsr_reports/{id}/approve', 'Admin\RsrReportController@approve');
    Route::get('add_rsr_stoppage_report/{id}', 'Admin\RsrReportController@addRsrStoppageReport');
    Route::post('get-rsr-images', 'Admin\RsrReportController@getImage')->name('getRsrImage');
    Route::get('search', 'Admin\RsrReportController@search')->name('rsrReport.search');

    Route::resource('availability_reports', 'Admin\AvailabilityReportController');
    Route::get('add-availability-report/{park_id}', 'Admin\AvailabilityReportController@addAvailabilityReport')->name('addAvailabilityReport');
    Route::get('show-availability-report', 'Admin\AvailabilityReportController@showAvailabilityReport')->name('reports.showAvailabilityReport');
    Route::get('all-reports', 'Admin\AvailabilityReportController@all')->name('availability_reports.all');
    Route::get('availability_report/{id}/{date}/approve', 'Admin\AvailabilityReportController@approve')->name('approveAvailabilityReport');
    Route::get('addOLdAvailabilityReport', 'Admin\AvailabilityReportController@addOLdAvailabilityReport')->name('addOLdAvailabilityReport');

    Route::get('rides-status', 'Admin\ReportsController@rideStatus')->name('reports.rideStatus');
    Route::get('operator-time-report', 'Admin\ReportsController@operatorTimeReport')->name('reports.operatorTimeReport');
    Route::get('attendance-time-report', 'Admin\ReportsController@attendanceTimeReport')->name('reports.attendanceTimeReport');
    Route::get('show-operator-time-report', 'Admin\ReportsController@showOperatorTimeReport')->name('reports.showOperatorTimeReport');
    Route::get('stoppages-report', 'Admin\ReportsController@stoppagesReport')->name('reports.stoppagesReport');
    Route::get('cycles-report', 'Admin\ReportsController@cyclesReport')->name('reports.cyclesReport');
    Route::get('queues-report', 'Admin\ReportsController@queuesReport')->name('reports.queuesReport');
    Route::get('show-stoppages-report', 'Admin\ReportsController@showstoppagesReport')->name('reports.showStoppagesReport');

    Route::resource('incidents', 'Admin\IncidentController');//done
    Route::get('/add_incident_report/{ride_id}/{park_time_id}', 'Admin\IncidentController@add_incident_report')->name('addIncidentReport');
    //Route::resource('questions','Admin\QuestionController');

    Route::resource('accidents', 'Admin\AccidentController');//done
    Route::get('/add_accident_report/{ride_id}/{park_time_id}', 'Admin\AccidentController@add_accident_report')->name('addAccidentReport');

    Route::resource('health_and_safety_reports', 'Admin\HealthAndSafetyReportController');//done
    Route::get('/add_health_and_safety_report/{park_id}/{time_slot_id}', 'Admin\HealthAndSafetyReportController@add_health_and_safety_report')->name('addHealthAndSafetyReport');
    Route::get('/edit_health_and_safety_report/{time_slot_id}', 'Admin\HealthAndSafetyReportController@edit_health_and_safety_report')->name('editHealthAndSafetyReport');
    Route::post('/updateRequest/', 'Admin\HealthAndSafetyReportController@update_request')->name('updateRequest');
    Route::get('/search_health_and_safety/', 'Admin\HealthAndSafetyReportController@search')->name('searchHealthAndSafetyReport');
    Route::get('/cheack_health/', 'Admin\HealthAndSafetyReportController@cheackHealth')->name('cheackHealth');
    /* Route::post('/updateRequest', function (Request $request) {
         dd('aaaaaaaaa');
     })->name('updateRequest');*/
    Route::resource('skill_game_reports', 'Admin\SkillGameReportController');//done
    Route::get('/add_skill_game_report/{park_id}/{time_slot_id}', 'Admin\SkillGameReportController@add_skill_game_report')->name('addSkillGameReport');
    Route::get('/edit_skill_game_report/{time_slot_id}', 'Admin\SkillGameReportController@edit_skill_game_report')->name('editSkillGameReport');
    Route::post('/updateskillGame/', 'Admin\SkillGameReportController@update_request')->name('updateskillGame');
    Route::get('/search_skill_game_reports/', 'Admin\SkillGameReportController@search')->name('searchSkillGameReport');
    Route::get('/cheack_skill_game/', 'Admin\SkillGameReportController@cheackSkillGame')->name('cheackSkillGame');

    Route::resource('maintenance_reports', 'Admin\MaintenanceReportController');//done
    Route::get('/add_maintenance_report/{park_id}/{time_slot_id}', 'Admin\MaintenanceReportController@add_maintenace_report')->name('addMaintenanceReport');
    Route::get('/edit_maintenance_report/{time_slot_id}', 'Admin\MaintenanceReportController@edit_maintenance_report')->name('editMaintenanceReport');
    Route::post('/updateMaintenance/', 'Admin\MaintenanceReportController@update_request')->name('updateMaintenance');
    Route::get('/search_maintenance_reports/', 'Admin\MaintenanceReportController@search')->name('searchMaintenanceReport');
    Route::get('/cheack_maintenance/', 'Admin\MaintenanceReportController@cheackMaintenance')->name('cheackMaintenance');

    Route::resource('tech-reports', 'Admin\TechReportsController');//done
    Route::get('/add-tech-report/{park_id}/{time_slot_id}', 'Admin\TechReportsController@add_tech_report')->name('addTechReport');
    Route::get('/edit_tech_report/{time_slot_id}', 'Admin\TechReportsController@edit_tech_report')->name('editTechReport');
    Route::post('/updateTechnical/', 'Admin\TechReportsController@update_request')->name('updateTechnical');
    Route::get('/search_tech_reports/', 'Admin\TechReportsController@search')->name('searchTechReport');
    Route::get('/cheack_tech/', 'Admin\TechReportsController@cheackTech')->name('cheackTech');

    Route::resource('ride-ops-reports', 'Admin\RideOpsReportsController');//done
    Route::get('/add-ride-ops-report/{park_id}/{time_slot_id}', 'Admin\RideOpsReportsController@add_ride_ops_report')->name('addOpsReport');
    Route::get('/edit_ride_ops_report/{time_slot_id}', 'Admin\RideOpsReportsController@edit_ride_ops_report')->name('editOpsReport');
    Route::post('/updateRideOps/', 'Admin\RideOpsReportsController@update_request')->name('updateRideOps');
    Route::get('/search_ride_ops_reports/', 'Admin\RideOpsReportsController@search')->name('searchOpsReport');
    Route::get('/cheack_ride_ops/', 'Admin\RideOpsReportsController@cheackRideOps')->name('cheackRideOps');

    Route::get('/search_duty_summary_reports/', 'Admin\DutySummaryController@search')->name('searchDutySummaryReport');

    Route::resource('duty-report', 'Admin\RideOpsReportsController');
    Route::get('inspection-list-report', 'Admin\ReportsController@inspectionListReport')->name('reports.inspectionListReport');
    Route::get('show-inspection-list-report', 'Admin\ReportsController@showInspectionListReport')->name('reports.showInspectionListReport');
    Route::get('show-inspections/{id}', 'Admin\ReportsController@showInspections')->name('show-inspections');

resources/views/admin/availability_reports/add.blade.php
@extends('admin.layout.app')

@section('title')
  Add New Availability Report
@endsection

@section('content')
    <div class="row">
        <div class="col-sm-12">
            <div class="card-box">
                <h4 class="header-title m-t-0 m-b-30">  Add New Availability Report</h4>
                        {!!Form::open( ['route' => 'admin.availability_reports.store' ,'class'=>'form phone_validate', 'method' => 'Post', 'enctype'=>"multipart/form-data",'class'=>'form-horizontal','files' => true]) !!}
                        @csrf
                        @include('admin.availability_reports.form')
                        {!!Form::close() !!}
            </div>
        </div><!-- end col -->
    </div>
    <!-- end row -->
@endsection
@push('scripts')
    <script>


    </script>
    {!! JsValidator::formRequest(\App\Http\Requests\Dashboard\Branch\BranchRequest::class, '#form'); !!}
@endpush

resources/views/admin/availability_reports/add_old_report.blade.php
@extends('admin.layout.app')

@section('title')
  Add An Old Availability Report
@endsection

@section('content')
    <div class="row">
        <div class="col-sm-12">
            <div class="card-box">
                <h4 class="header-title m-t-0 m-b-30">  Add An Old Availability Report</h4>
                        {!!Form::open( ['route' => 'admin.availability_reports.store' ,'class'=>'form phone_validate', 'method' => 'Post', 'enctype'=>"multipart/form-data",'class'=>'form-horizontal','files' => true]) !!}
                        @csrf
{{--@include('admin.common.errors')--}}
<div class="row">
    <div class="col-sm-12">
        <div class="form-group">
            <label for="middle_name">Time Slot Date </label>
            {!! Form::date('date', \Carbon\Carbon::now()->toDate(), ['class' => 'form-control', 'id' => 'date']) !!}
        </div>
      
        <div class='responsive-wrapper'>
            <table id="datatable-buttons" class="table table-striped table-bordered dt-responsive nowrap">
                <thead>
                <tr role="row">
                    <th class="sorting_asc" tabindex="0" aria-controls="datatable-buttons" rowspan="1"
                        colspan="1" aria-sort="ascending">ID
                    </th>
                    <th class="sorting" tabindex="0" aria-controls="datatable-buttons" rowspan="1" colspan="1">
                        Ride
                    </th>
                    <th class="sorting" tabindex="0" aria-controls="datatable-buttons" rowspan="1" colspan="1">
                        First Status
                    </th>
                    <th class="sorting" tabindex="0" aria-controls="datatable-buttons" rowspan="1" colspan="1">
                        Second Status
                    </th>
                    <th class="sorting" tabindex="0" aria-controls="datatable-buttons" rowspan="1" colspan="1">
                        No Of Gondolas
                    </th>
                    <th class="sorting" tabindex="0" aria-controls="datatable-buttons" rowspan="1" colspan="1">
                        No Of Seats
                    </th>
                    <th class="sorting" tabindex="0" aria-controls="datatable-buttons" rowspan="1" colspan="1">
                        Comment
                    </th>
                </tr>
                </thead>
                <tbody>
                @foreach ($rides as $item)

                    <tr role="row" class="odd" id="row-{{ $item->id }}">
                        <td tabindex="0" class="sorting_1">{{ $item->id }}</td>
                        <td> {{$item->name}}
                            <input type="hidden" name="ride_id[]" value=" {{$item->id}}">
                            <input type="hidden" name="park_id" value=" {{$item->park_id}}">
                        </td>
                        <td>
                            <label>
                                <select name="first_status[]" id="element_id" data-id="{{$item->id}}"
                                        class="form-control element-id">
                                    <option default value=""></option>
                                    <option value="yes" selected>Yes</option>
                                    <option value="no">No</option>
                                </select>
                            </label>
                        </td>
                        <td><label></label></td>


                        <td> {!! Form::number("no_of_gondolas[]",$item->no_of_gondolas,['class'=>'form-control','placeholder'=>' number_of_gondolas'])!!}</td>
                        <td> {!! Form::number("no_of_seats[]",$item->capacity_one_cycle,['class'=>'form-control','placeholder'=>' number_of_seats'])!!}</td>                          
                        <td id="comment{{$item->id}}"> {!! Form::textArea("comment[]",null,['class'=>'form-control','placeholder'=>'Comment'])!!}
                        </td>
                    </tr>
                @endforeach
                </tbody>
            </table>
        </div>
    </div>

    <div class="col-xs-12 aligne-center contentbtn">
        <button class="btn btn-primary waves-effect" type="submit">Save</button>
    </div>
</div>

                        {!!Form::close() !!}
            </div>
        </div><!-- end col -->
    </div>
    <!-- end row -->
@endsection
@push('scripts')
    <script>


    </script>
    {!! JsValidator::formRequest(\App\Http\Requests\Dashboard\Branch\BranchRequest::class, '#form'); !!}
@endpush

resources/views/admin/availability_reports/ajax.blade.php
<div class="font-bold m-3 text-center">
    @if($outRang)
        <span class="font-bold m-3 text-danger">Filter out of range</span>
    @else
        <span class="font-bold m-3 text-danger">Total Count</span> : @if (isset($items))
            {{$items->count()}}
        @else
            0
        @endif
    @endif
</div>
@if(isset($items) && count($items) >0)
    <div class="form-group left row col-md-12">
        <a class="btn btn-info" href="{{ route('admin.export.availability',$items->pluck('id')) }}">Export File Csv</a>

    </div>
    <div id="datatable-buttons_wrapper" class="dataTables_wrapper dt-bootstrap4 no-footer">
        <div class="row">
            {{--        <div class="col-xs-12">--}}
            {{--            <input type="button" value="Print Report" id="printDiv" class="btn btn-primary printBtn"></input>--}}
            {{--        </div>--}}
            <div class="col-xs-12 printable_div" id="myDivToPrint">
                <div class="col-xs-12 printOnly">
                    <div class="logo">
                        <img src="{{ asset('/_admin/assets/images/logo1.png') }}" alt="Mellors-img" title="Mellors"
                             class="image">
                    </div>
                    <h3 class="table-title">Ride Availability Report</h3>
                </div>
                <div class="col-xs-12">
                    <div class='responsive-wrapper'>
                        <table id="datatable-buttons" class="table table-striped table-bordered dt-responsive nowrap">
                            <thead>
                            <tr role="row">
                                <th class="sorting_asc" tabindex="0" aria-controls="datatable-buttons" rowspan="1"
                                    colspan="1" aria-sort="ascending">ID
                                </th>
                                <th class="sorting" tabindex="0" aria-controls="datatable-buttons" rowspan="1"
                                    colspan="1">
                                    Park
                                </th>
                                <th class="sorting" tabindex="0" aria-controls="datatable-buttons" rowspan="1"
                                    colspan="1">
                                    Zone
                                </th>
                                <th class="sorting" tabindex="0" aria-controls="datatable-buttons" rowspan="1"
                                    colspan="1">
                                    Ride
                                </th>

                                <th class="sorting" tabindex="0" aria-controls="datatable-buttons" rowspan="1"
                                    colspan="1">
                                    Time Slot Date
                                </th>
                                <th class="sorting" tabindex="0" aria-controls="datatable-buttons" rowspan="1"
                                    colspan="1">
                                    First Status
                                </th>
                                <th class="sorting" tabindex="0" aria-controls="datatable-buttons" rowspan="1"
                                    colspan="1">
                                    Second Status
                                </th>
                                <th class="sorting" tabindex="0" aria-controls="datatable-buttons" rowspan="1"
                                    colspan="1">
                                    No Of Gondolas
                                </th>
                                <th class="sorting" tabindex="0" aria-controls="datatable-buttons" rowspan="1"
                                    colspan="1">
                                    No Of Seats
                                </th>
                                <th class="sorting" tabindex="0" aria-controls="datatable-buttons" rowspan="1"
                                    colspan="1">
                                    Comment
                                </th>
                            </tr>
                            </thead>

                            <tbody>
                            @if (isset($items))
                                @foreach ($items as $item)
                                    <tr role="row" class="odd" id="row-{{ $item->id }}">
                                        <td tabindex="0" class="sorting_1">{{ $item->id }}</td>
                                        <td>{{ $item->parks?->name }}</td>
                                        <td>{{ $item->zone?->name }}</td>
                                        <td>{{ $item->rides?->name }}</td>
                                        <td>{{ $item->date }}</td>
                                        <td>{{ $item->first_status }}</td>
                                        <td>{{ $item->second_status }}</td>
                                        <td>{{ $item->no_of_gondolas }}</td>
                                        <td>{{ $item->no_of_seats }}</td>
                                        <td>{!! $item->comment !!} </td>
                                    </tr>
                                @endforeach
                            @endif

                            </tbody>
                        </table>


                    </div>
                </div>
            </div>
        </div>

    </div>
@endif

resources/views/admin/availability_reports/all_reports.blade.php
@extends('admin.layout.app')

@section('title')
 Availability Reports 
@endsection

@section('content')

    <div class="card-box">

        <div id="datatable-buttons_wrapper" class="dataTables_wrapper dt-bootstrap4 no-footer">
            <div class="row">
                <div class="col-sm-12">
                    <div class='responsive-wrapper'>
                    <table id="datatable-buttons" class="table table-striped table-bordered dt-responsive nowrap">
                        <thead>
                        <tr role="row">
                            <th class="sorting_asc" tabindex="0" aria-controls="datatable-buttons" rowspan="1"
                                colspan="1" aria-sort="ascending">ID
                            </th>
                            <th class="sorting" tabindex="0" aria-controls="datatable-buttons" rowspan="1" colspan="1">
                                Park
                            </th>
                            @if(auth()->user()->can('approve-availabilty-report'))  

                            <th class="sorting" tabindex="0" aria-controls="datatable-buttons" rowspan="1" colspan="1">
                                Status
                            </th>
                            @endif
                            <th class="sorting" tabindex="0" aria-controls="datatable-buttons" rowspan="1" colspan="1">
                                Reported_by
                            </th> <th class="sorting" tabindex="0" aria-controls="datatable-buttons" rowspan="1" colspan="1">
                              Time Slot Date
                            </th>
                            <th class="sorting" tabindex="0" aria-controls="datatable-buttons" rowspan="1" colspan="1">
                                Process
                            </th>
                        </tr>
                        </thead>

                        <tbody>
                        @if(isset($items))

                        @foreach ($items as $item)
                            <tr role="row" class="odd" id="row-{{ $item->id }}">
                                <td tabindex="0" class="sorting_1">{{ $item->id}}</td>
                                <td>{{ $item->parks->name??'' }}</td>                               
                                @if(auth()->user()->can('approve-availabilty-report'))  
                                <td>

                                 @if($item->status=='pending')
                                 <a href="{{ url('availability_report/' . $item->park_id . '/' . $item->date . '/approve') }}"
                                  class="btn btn-xs btn-danger"><i class="fa fa-check"></i> Approve</a>
                                  @endif
                                  @if($item->status=='approved')
                                <span>Verified</span>
                                    @endif
                                </td>
                                @endif

                                <td>{{ $item->created_by->name ??''}}</td>
                                <td>{{ $item->date }}</td>
                                <td>
                                    @if(auth()->user()->can('show-availabilty-report'))
                                        <a href="{{ route('admin.availability_reports.show', $item->park_id) }}"
                                           class="btn btn-primary">Show</a>
                                    @endif

                                    @if(auth()->user()->can('availability_reports-edit'))
                                    <a href="{{ route('admin.availability_reports.edit', $item->park_id) }}"
                                    class="btn btn-success">Edit</a>
                                    @endif

                                </td>

                            </tr>

                        @endforeach
                            @endif
                        </tbody>
                    </table>


                </div>
                </div>
            </div>

        </div>
    </div>


@endsection


@section('footer')
    @include('admin.datatable.scripts')
@endsection

resources/views/admin/availability_reports/edit.blade.php
@extends('admin.layout.app')

@section('title','Add Second Status ')

@section('content')
    <div class="row">
        <div class="col-sm-12">
            <div class="card-box">
                <h4 class="header-title m-t-0 m-b-30">Add Second Status</h4>
              
                            {!!Form::model($items , ['route' => ['admin.availability_reports.update' , $id] ,
                             'method' => 'PATCH','enctype'=>"multipart/form-data",'files' => true,'id'=>'form']) !!}
                            @include('admin.availability_reports.form_edit')
                            {!!Form::close() !!}
            </div>
        </div><!-- end col -->
    </div>
    <!-- end row -->
@endsection
@push('scripts')
    {!! JsValidator::formRequest(\App\Http\Requests\Dashboard\Branch\BranchRequest::class, '#form'); !!}
@endpush

resources/views/admin/availability_reports/index.blade.php
@extends('admin.layout.app')

@section('title')
    Ride Availability Report
@endsection

@section('content')

    <div class="card-box">
        <form class="formSection" method="GET">
            <div class="row">
                <div class='col-md-4'>
                    <div class="form-group">
                        <label for="last_name">Select Park</label>
                        {!! Form::select('park_id', $parks, null, [
                            'class' => 'form-control park',
                            'id' => 'park',
                            'placeholder' => 'Choose Park',
                        ]) !!}
                    </div>
                </div>
                <div class='col-md-4'>
                    <div class="form-group">
                        <label for="last_name">Select Zone</label>
                        {!! Form::select('zone_id', [], null, [
                            'class' => 'form-control ride',
                            'id' => 'zone',
                            'placeholder' => 'Choose Zone',
                        ]) !!}
                    </div>
                </div>

                <div class='col-md-4'>
                    <div class="form-group">
                        <label for="last_name">Select Ride</label>
                        {!! Form::select('ride_id', [], null, [
                            'class' => 'form-control ride',
                            'id' => 'ride',
                            'placeholder' => 'Choose Ride',
                        ]) !!}
                    </div>
                </div>

                <div class='col-md-5'>
                    <div class="form-group">
                        <label for="middle_name">Time Slot Date From </label>
                        {!! Form::date('from',\Carbon\Carbon::now()->toDate(),['class'=>'form-control','id'=>'date']) !!}
                    </div>
                </div>
                <div class='col-md-5'>
                    <div class="form-group">
                        <label for="middle_name">Time Slot Date To </label>
                        {!! Form::date('to',\Carbon\Carbon::now()->toDate(),['class'=>'form-control','id'=>'date']) !!}
                    </div>
                </div>
                <div class='col-md-2 mtButton'>
                    <div class="input-group-btn">
                        <button type="button" class="btn btn-primary save_btn waves-effect">Show</button>
                    </div>
                </div>
            </div>
        {!! Form::close() !!}
    </div>
    <br><br>
    <div id="items">


    </div>

@endsection
@push('scripts')
    <script type="text/javascript">
        $("#park").change(function () {
            $.ajax({
                url: "{{ route('admin.getParkZones') }}?park_id=" + $(this).val(),
                method: 'GET',
                success: function (data) {
                    $('#zone').html(data.html);
                }
            });
        });
        $("#zone").change(function () {
            $.ajax({
                url: "{{ route('admin.getZonerides') }}?zone_id=" + $(this).val(),
                method: 'GET',
                success: function (data) {
                    $('#ride').html(data.html);
                }
            });
        });
    </script>
    <script language="javascript">
        $('#printDiv').click(function () {
            $('#myDivToPrint').show();
            window.print();
            return false;
        });
        $(document).on("click", ".save_btn", function () {

            var park = $('#park').val();
            var ride = $('#ride').val();
            var from = $('#date').val();
            var to = $('#date_to').val();
            $.ajax({
                url: "{{ route('admin.availability_reports.index') }}",
                method: 'GET',
                data: {
                    park_id: park,
                    ride_id: ride,
                    from: from,
                    to: to,
                },
                success: function (data) {
                    console.log(data)
                    $('#items').html(' ');
                    $('#items').html(data);

                }
            });
        });
    </script>
@endpush
@section('footer')
    @include('admin.datatable.scripts')
@endsection