routes/web.php
    Route::get('queues/time/{id}', 'Admin\QueueController@queuesTime')->name('queue.time');
    Route::get('queues/ride/{id}/{time}', 'Admin\QueueController@queuesRide')->name('queue.ride');


    Route::get('statistics', 'Admin\IndexController@statistics')->name('statistics');
    Route::get('statistics/park/{id}', 'Admin\IndexController@statisticPark')->name('statisticPark');
    Route::get('make_all_read', 'Admin\IndexController@makeAllRead')->name('makeAllRead');
    Route::get('all_notifications', 'Admin\IndexController@allNotifications')->name('allNotifications');
    Route::resource('roles', 'Admin\RoleController'); // done
    Route::resource('users', 'Admin\UserController'); // done
    Route::resource('attendances', 'Admin\AttendanceController'); // done
    Route::get('upload-attendance', 'Admin\AttendanceController@uploadAttendance')->name('uploadAttendance');
    Route::post('upload-attendance-excle', 'Admin\AttendanceController@uploadAttendancesExcleFile')->name('uploadAttendancesExcleFile');
    Route::get('upload-attendance-time', 'Admin\AttendanceController@uploadAttendanceTime')->name('uploadAttendanceTime');
    Route::post('upload-attendance-time-excle', 'Admin\AttendanceController@uploadAttendancesTimeExcleFile')->name('uploadAttendancesTimeExcleFile');

    Route::get('attendance_show_time/{attendanceLog}', 'Admin\AttendanceController@show_time')->name('show_time');
    Route::get('attendance_update-time', 'Admin\AttendanceController@show_time_update')->name('show_time_update');
    Route::get('attendance_time_delete/{attendanceLog}', 'Admin\AttendanceController@delete')->name('attendance-time-delete');
    Route::get('attendance_add_time/{id}', 'Admin\AttendanceController@addTime')->name('addTime');
    Route::Post('store_time', 'Admin\AttendanceController@StoreTime')->name('attendances.store_time');

    Route::resource('operators', 'Admin\OperatorController');
    Route::get('operator_add_time/{id}', 'Admin\OperatorController@addTime')->name('operatorAddTime');
    Route::get('upload-operator-time', 'Admin\OperatorController@uploadOperatorTime')->name('uploadOperatorTime');
    Route::post('upload-operator-time-excle', 'Admin\OperatorController@uploadOperatorTimeExcleFile')->name('uploadOperatorTimeExcleFile');


    Route::get('operator_update-time', 'Admin\ReportsController@operator_show_time_update')->name('operator-show-time-update');
    Route::get('operator_time_delete/{userLog}', 'Admin\ReportsController@delete_operator_time')->name('operator-time-delete');

    Route::resource('departments', 'Admin\DepartmentController');

    Route::resource('branches', 'Admin\BranchController');//done
    Route::resource('parks', 'Admin\ParkController');//done
    Route::get('get_by_branch', 'Admin\ParkController@get_by_branch')->name('parks.get_by_branch');
    Route::resource('zones', 'Admin\ZoneController');//done
    Route::resource('versions', 'Admin\MobileVersionsController');//done
    Route::get('get_by_branch_id', 'Admin\ZoneController@get_by_branch')->name('zones.get_by_branch');


    Route::resource('park_without_times', 'Admin\ParkWithoutTimeController');//done
    Route::get('/search_park_without_times/', 'Admin\ParkWithoutTimeController@search')->name('search_park_without_times');

    Route::resource('park_times', 'Admin\ParkTimeController');//done
    Route::resource('schedule_park_times', 'Admin\ScheduleParkTimeController');
    Route::get('/search_park_times/', 'Admin\ParkTimeController@search');

    Route::resource('game_times', 'Admin\GameTimeController');//done
    Route::get('/edit_ride_time/{ride_id}/{park_time_id}', 'Admin\GameTimeController@edit_ride_time')->name('editRideTime');

    Route::PATCH('daily_entrance_count', 'Admin\ParkTimeController@add_daily_entrance_count')->name('park_times.daily_entrance_count');
    Route::get('/all-rides/{park_id}/{time_slot_id}', 'Admin\GameTimeController@all_rides')->name('allRides');

    Route::get('/game-all-times/{id}', 'Admin\GameTimeController@all_times');

    Route::resource('ride_types', 'Admin\RideTypeController');
    Route::resource('games', 'Admin\GameController');//done

    //operation
    Route::resource('stoppage-category', 'Admin\StoppageCategoryController');//done
    Route::resource('stoppage-sub-category', 'Admin\StoppageSubCategoryController');//done
    Route::resource('rides', 'Admin\RidesController');//done
    Route::delete('destroy_park/{id}', 'Admin\RidesController@destroyPark')->name('destroy_park');


    Route::get('upload-rides', 'Admin\RidesController@uploadRides')->name('uploadRides');
    Route::Post('upload-rides-with-excel', 'Admin\RidesController@uploadExcleFile')->name('uploadExcleFile');

    Route::resource('rides-stoppages', 'Admin\RideStoppageController');//done
    Route::get('/search_stoppages/', 'Admin\RideStoppageController@search')->name('searchStoppage');
    Route::Post('upload-stoppages-with-excel', 'Admin\RideStoppageController@uploadStoppagesExcleFile')->name('uploadStoppagesExcleFile');
    Route::post('get-images', 'Admin\RideStoppageController@getImage')->name('getImage');
    Route::get('/show_stoppages/{ride_id}/{park_time_id}', 'Admin\RideStoppageController@show_stoppages')->name('showStoppages');
    Route::get('/add_stoppage/{ride_id}/{park_time_id}', 'Admin\RideStoppageController@add_stoppage')->name('addStoppage');
    Route::PATCH('update_stoppage_status', 'Admin\RideStoppageController@extend')->name('rides-stoppages.updateStoppageStatus');
    Route::get('solve_stoppage/{id}', 'Admin\RideStoppageController@solveStoppage')->name('solveStoppage');

    Route::resource('rides-cycles', 'Admin\RideCyclesController');//done
    Route::Post('upload-cycles-with-excel', 'Admin\RideCyclesController@uploadCycleExcleFile')->name('uploadCycleExcleFile');
    Route::get('/search_ride_cycle/', 'Admin\RideCyclesController@search')->name('searchRideCycle');
    Route::get('/show_cycles/{ride_id}/{park_time_id}', 'Admin\RideCyclesController@show_cycles')->name('showCycles');
    Route::get('/add_cycle/{ride_id}/{park_time_id}', 'Admin\RideCyclesController@add_cycle')->name('addCycle');

    Route::resource('queues', 'Admin\QueueController');//done
    Route::Post('upload-queues-with-excel', 'Admin\QueueController@uploadQueueExcleFile')->name('uploadQueueExcleFile');
    Route::get('/search_queues/', 'Admin\QueueController@search')->name('search');
    Route::get('/show_queues/{ride_id}/{park_time_id}', 'Admin\QueueController@show_queues')->name('showQueues');
    Route::get('/add_queue/{ride_id}/{park_time_id}', 'Admin\QueueController@add_queue')->name('addQueue');

    Route::resource('inspection_lists', 'Admin\InspectionListController');//done

    Route::resource('preopening_lists', 'Admin\PreopeningListController');//done
    Route::get('/add_preopening_list_to_ride/{ride_id}/{park_time_id}', 'Admin\PreopeningListController@add_preopening_list_to_ride');
    Route::post('/update_preopening_list/{preopen_info_id}/', 'Admin\PreopeningListController@update_ride_preopening_list')->name('updatePreopeningList');
    Route::get('/cheack_preopening_list/', 'Admin\PreopeningListController@cheackPreopeningList')->name('cheackPreopeningList');
    Route::get('/show_preopening_list/{ride_id}/{park_time_id}', 'Admin\PreopeningListController@show_ride_preopening_list')->name('showPreopeningList');
    Route::get('/delete_preopening/{id}/{park_id}/{park_time_id}', 'Admin\PreopeningListController@deletePreopenetng')->name('deletePreopeningList');

    Route::resource('general_questions', 'Admin\GeneralQuestionsController');//done

    Route::get('/show_general_questions/{ride_id}/{park_time_id}', 'Admin\GeneralQuestionsController@show_questions')->name('show_questions');
    Route::get('/add_general_questions/{ride_id}/{park_time_id}', 'Admin\GeneralQuestionsController@add_general_questions');
    Route::get('/edit_questions/{id}', 'Admin\GeneralQuestionsController@edit')->name('edit_questions');
    Route::get('/show_questions_list/{id}', 'Admin\GeneralQuestionsController@show_questions_list')->name('show_questions_list');
    Route::post('/update_questions/{id}', 'Admin\GeneralQuestionsController@update')->name('update_questions');
    Route::post('/store_questions', 'Admin\GeneralQuestionsController@store')->name('store_questions');
    Route::get('questions/{id}/approve', 'Admin\GeneralQuestionsController@approve');


    Route::get('/zone_rides/{zone_id}', 'Admin\PreopeningListController@zone_rides')->name('zoneRides');
    Route::resource('ride_inspection_lists', 'Admin\RideInspectionListController');
    Route::get('/add_ride_inspection_lists/{ride_id}', 'Admin\RideInspectionListController@add_ride_inspection_lists')->name('addRideInspectionLists');
    Route::get('/cheack_ride_inspection_lists/', 'Admin\RideInspectionListController@cheackRideInspectionList')->name('cheackRideInspectionList');
    Route::get('/edit_ride_inspection_lists/{ride_id}', 'Admin\RideInspectionListController@edit_ride_inspection_lists')->name('editRideInspectionLists');
    Route::post('/update_ride_inspection_lists/{ride_id}', 'Admin\RideInspectionListController@update_ride_inspection_lists')->name('updatRideInspectionLists');

    Route::resource('zone_inspection_lists', 'Admin\ZoneInspectionListController');
    Route::get('/add_zone_inspection_lists/{zone_id}', 'Admin\ZoneInspectionListController@add_zone_inspection_lists')->name('addZoneInspectionLists');
    Route::get('/cheack_zone_inspection_lists/', 'Admin\ZoneInspectionListController@cheackzoneInspectionList')->name('cheackZoneInspectionList');
    Route::get('/edit_zone_inspection_lists/{zone_id}', 'Admin\ZoneInspectionListController@edit_zone_inspection_lists')->name('editZoneInspectionLists');
    Route::post('/update_zone_inspection_lists/{zone_id}', 'Admin\ZoneInspectionListController@update_zone_inspection_lists')->name('updatZoneInspectionLists');

    Route::resource('complaints', 'Admin\CustomerComplaintController');//done

app/Models/ScheduleParkTime.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class ScheduleParkTime extends Model
{
    use HasFactory;
    protected $guarded = [];
    public function park()
    {
        return $this->belongsTo(Park::class,'park_id');

    }
}

app/Http/Controllers/Admin/ScheduleParkTimeController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\Dashboard\ScheduleParkTimeRequest;
use App\Models\Park;
use App\Models\ParkTime;
use App\Models\ScheduleParkTime;
use Illuminate\Support\Carbon;


class ScheduleParkTimeController extends Controller
{

    public function index()
    {
        if (auth()->user()->hasRole('Super Admin')) {
            $parks = Park::pluck('id');
        } else {
            $parks = auth()->user()->parks->pluck('id');
        }

        if (auth()->user()->hasRole('Super Admin')) {
            $items = ScheduleParkTime::whereNull('parent_id')->get();
        } else {
            $items = ScheduleParkTime::whereIn('park_id', $parks)->whereNull('parent_id')->get();
        }


        return view('admin.schedule_park_times.index', compact('parks', 'items'));
    }


    public function create()
    {
        if (auth()->user()->hasRole('Super Admin')) {
            $parks = Park::pluck('name', 'id')->toArray();
        } else {
            $parks = auth()->user()->parks->pluck('name', 'id')->toArray();
        }
        return view('admin.schedule_park_times.add', compact('parks'));
    }


    public function store(ScheduleParkTimeRequest $request)
    {

        $data = $request->validated();
        $startDate = Carbon::parse($data['start_date']);
        $endDate = Carbon::parse($data['end_date']);
        $dates = [];
        while ($startDate->lte($endDate)) {
            $dates[] = $startDate->toDateString(); // Add the date to the array
            $startDate->addDay(); // Move to the next day
        }
        $parent = ScheduleParkTime::create($data);
        foreach ($dates as $date) {
            ScheduleParkTime::query()->create([
                'start_date' => $date,
                'end_date' => Carbon::parse($date)->addDay(),
                'start' => $data['start'],
                'end' => $data['end'],
                'park_id' => $data['park_id'],
                'parent_id' => $parent->id,
            ]);
        }


        alert()->success('Schedule Time Slot Added successfully');
        return redirect()->route('admin.schedule_park_times.index');
    }


    public function edit($id)
    {
        $time = ScheduleParkTime::find($id);
        $parks = Park::pluck('name', 'id')->all();
        return view('admin.schedule_park_times.edit', compact('parks', 'time'));
    }


    public function update(ScheduleParkTimeRequest $request, ScheduleParkTime $scheduleParkTime)
    {

        $data = $request->validated();
        $scheduleParkTime->update($data);
        ScheduleParkTime::where('parent_id',$scheduleParkTime->id)->delete();
        $startDate = Carbon::parse($data['start_date']);
        $endDate = Carbon::parse($data['end_date']);
        $dates = [];
        while ($startDate->lte($endDate)) {
            $dates[] = $startDate->toDateString(); // Add the date to the array
            $startDate->addDay(); // Move to the next day
        }
        foreach ($dates as $date) {
            ScheduleParkTime::query()->create([
                'start_date' => $date,
                'end_date' => Carbon::parse($date)->addDay(),
                'start' => $data['start'],
                'end' => $data['end'],
                'park_id' => $data['park_id'],
                'parent_id' => $scheduleParkTime->id,
            ]);
        }
        alert()->success('Schedule Park Time Slot Updated successfully !');
        return redirect()->route('admin.schedule_park_times.index');
    }


    public function destroy($id)
    {

        $parkTime = ScheduleParkTime::find($id);
        ScheduleParkTime::where('parent_id',$parkTime->id)->delete();
        $parkTime->delete();
        alert()->success('Schedule Park Time Slot deleted successfully');
        return back();

    }


}

resources/views/admin/schedule_park_times/action.blade.php
<div class="d-inline-flex">
    @can('park_times-edit')
    <a  href="{{route('admin.park_times.edit',$id)}}"><button class="btn btn-warning">Edit</button></a>
    @endcan
    @can('park_times-delete')
    <a onclick=" $('#delete-form-{{$id}}').submit();" ><div class="btn btn-danger">Delete</div></a>
    {!! Form::open(['route'=>['admin.park_times.destroy',$id],'method'=>'DELETE','id'=>'delete-form-'.$id]) !!}
    {!! Form::close() !!}
        @endcan
</div>

resources/views/admin/schedule_park_times/add.blade.php
@extends('admin.layout.app')

@section('title')
  Add Time Slot To The Park
@endsection

@section('content')
    <div class="row">
        <div class="col-sm-12">
            <div class="card-box">
                <h4 class="header-title m-t-0 m-b-30">  Add Time Slot To The Park</h4>
                        {!!Form::open( ['route' => 'admin.schedule_park_times.store' ,'class'=>'form phone_validate', 'method' => 'Post', 'enctype'=>"multipart/form-data",'class'=>'form-horizontal','files' => true]) !!}
                        @csrf
                        @include('admin.schedule_park_times.form')
                        {!!Form::close() !!}
            </div>
        </div><!-- end col -->
    </div>
    <!-- end row -->
@endsection
@push('scripts')
    {!! JsValidator::formRequest(\App\Http\Requests\Dashboard\ParkTime\ParkTimeRequest::class, '#form'); !!}
@endpush

resources/views/admin/schedule_park_times/edit.blade.php
@extends('admin.layout.app')

@section('title','Update Park Time Slot :'.$time->park->name)

@section('content')
    <div class="row">
        <div class="col-sm-12">
            <div class="card-box">
                <h4 class="header-title m-t-0 m-b-30">Update Schedule Park Time Slot : {{ $time->park->name }} </h4>
                <a class="input-group-btn" href="{{route('admin.schedule_park_times.index')}}">
                    <button type="button" class="btn waves-effect waves-light btn-primary">back</button>
                </a>
                            {!!Form::model($time , ['route' => ['admin.schedule_park_times.update' , $time->id] , 'method' => 'PATCH','enctype'=>"multipart/form-data",'files' => true,'id'=>'form']) !!}
                            @include('admin.schedule_park_times.form')
                            {!!Form::close() !!}
            </div>
        </div><!-- end col -->
    </div>
    <!-- end row -->
@endsection
@push('scripts')
{{--    {!! JsValidator::formRequest(\App\Http\Requests\Dashboard\ParkTime\ParkTimeRequest::class, '#form'); !!}--}}
@endpush

resources/views/admin/schedule_park_times/form.blade.php
{{--@include('admin.common.errors')--}}
<div class="row">

    <div class="form-group">
        <div class="col-lg-12">
            Park :</label>
        </div>
        <div class="col-lg-12">
            {!! Form::select('park_id', $parks,null, array('class' => 'form-control col-lg-6 select2')) !!}
        </div>
    </div>
    <div class="form-group">
        <div class="col-lg-12">
            {!! Form::label('Open Date') !!}
        </div>
        <div class="col-lg-12">
        {!! Form::date('start_date',$time->start_date?? \Carbon\Carbon::now()->toDateString(), ['class' => 'form-control']) !!}
            @if ($errors->has('start_date'))
            <span class="help-block">
                <strong>{{ $errors->first('start_date') }}</strong>
            </span>
            @endif
        </div>
    </div>
    <div class="form-group">
        <div class="col-lg-12">
            {!! Form::label('Start Time') !!}
        </div>
        <div class="col-lg-12">
        {!! Form::time('start',$time->start?? \Carbon\Carbon::now()->format('H:i'), ['class' => 'form-control']) !!}
            @if ($errors->has('start'))
            <span class="help-block">
                <strong>{{ $errors->first('start') }}</strong>
            </span>
            @endif
        </div>
    </div>
    <div class="form-group">
        <div class="col-lg-12">
            {!! Form::label('Close Date') !!}
        </div>
        <div class="col-lg-12">
        {!! Form::date('end_date',$time->end_date?? \Carbon\Carbon::now()->toDateString(), ['class' => 'form-control']) !!}
            @if ($errors->has('end_date'))
            <span class="help-block">
                <strong>{{ $errors->first('end_date') }}</strong>
            </span>
            @endif
        </div>
    </div>
    <div class="form-group">
        <div class="col-lg-12">
            {!! Form::label('Closed Time') !!}
        </div>
        <div class="col-lg-12">
        {!! Form::time('end',$time->end?? \Carbon\Carbon::now()->format('H:i'), ['class' => 'form-control']) !!}
            @if ($errors->has('end'))
            <span class="help-block">
                <strong>{{ $errors->first('end') }}</strong>
            </span>
            @endif
        </div>
    </div>
    <br>
    <br>
    <div class="col-xs-12 aligne-center contentbtn">
        <button class="btn btn-primary waves-effect" type="submit">Save</button>
    </div>
</div>

resources/views/admin/schedule_park_times/index.blade.php
@extends('admin.layout.app')

@section('title')
    Schedule Parks Time Slot
@endsection

@section('content')

    <div class="card-box">

        <div id="datatable-buttons_wrapper" class="dataTables_wrapper dt-bootstrap4 no-footer">
            <div class="row">
                <div class="col-sm-12">
                    <table id="datatable-buttons" class="table table-striped table-bordered dt-responsive nowrap">
                        <thead>
                        <tr role="row">
                            <th class="sorting_asc" tabindex="0" aria-controls="datatable-buttons" rowspan="1"
                                colspan="1" aria-sort="ascending">ID
                            </th>
                            <th class="sorting" tabindex="0" aria-controls="datatable-buttons" rowspan="1"
                                colspan="1">
                                Park
                            </th>
                            <th class="sorting" tabindex="0" aria-controls="datatable-buttons" rowspan="1"
                                colspan="1">
                                Open Date
                            </th>
                            <th class="sorting" tabindex="0" aria-controls="datatable-buttons" rowspan="1"
                                colspan="1">
                                Open Time
                            </th>
                            <th class="sorting" tabindex="0" aria-controls="datatable-buttons" rowspan="1"
                                colspan="1">
                                Close Date
                            </th>
                            <th class="sorting" tabindex="0" aria-controls="datatable-buttons" rowspan="1"
                                colspan="1">
                                Close Time
                            </th>


                            <th class="sorting" tabindex="0" aria-controls="datatable-buttons" rowspan="1"
                                colspan="1">
                                Process
                            </th>
                        </tr>
                        </thead>

                        <tbody>
                        @foreach ($items as $item)

                                <tr role="row" class="odd" id="row-{{ $item->id }}">

                                    <td tabindex="0" class="sorting_1">{{ $item->id }}
                                        <input type="hidden" name="park_time_id" id="park-time-id" class="park-time-id"
                                               value="{{ $item->id }}">
                                    </td>
                                    <td>{{ $item->park->name }}</td>
                                    <td>{{ $item->start_date }}</td>
                                    <td>{{ $item->start }}</td>
                                    <td>{{ $item->end_date }}</td>
                                    <td>{{ $item->end }}</td>

                                   <td>

                                       <a href="{{ route('admin.schedule_park_times.edit', $item) }}" class="btn btn-info">Edit</a>
                                       <a class="btn btn-danger" data-name="{{ $item->name }}"
                                          data-url="{{ route('admin.schedule_park_times.destroy', $item) }}"
                                          onclick="delete_form(this)">
                                           Delete
                                       </a>
                                   </td>


                                </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>

@endsection
@push('scripts')
    <script type="text/javascript">
        $("#ClientStore").popover({
            title: '<h4>Add Daily Entrance Count</h4>',
            container: 'body',
            placement: 'bottom',
            html: true,
            content: function () {
                return $('#popover-form').html();
            }
        });
    </script>
@endpush

@section('footer')
    @include('admin.datatable.scripts')
@endsection