routes/web.php
    Route::get('/edit_zone_weekly_elements/{zone_id}', 'Admin\ZoneWeeklyController@edit_zone_weekly_elements');
    Route::post('/update_zone_weekly_elements/{zone_id}', 'Admin\ZoneWeeklyController@update_zone_weekly_elements')->name('updatZoneWeeklyElements');

    Route::resource('zone_daily', 'Admin\ZoneDailyController');
    Route::get('/add_zone_daily_elements/{zone_id}', 'Admin\ZoneDailyController@add_zone_daily_elements');
    Route::get('/edit_zone_daily_elements/{zone_id}', 'Admin\ZoneDailyController@edit_zone_daily_elements');
    Route::post('/update_zone_daily_elements/{zone_id}', 'Admin\ZoneDailyController@update_zone_daily_elements')->name('updatZoneDailyElements');

    Route::get('show_zone_preclose_list/{zone_id}/{date}', 'Admin\ZonePreclosingController@show_zone_preclose_list')->name('show_zone_preclose_list');
    Route::get('show_zone_preopen_list/{zone_id}/{date}', 'Admin\ZonePreopeningController@show_zone_preopen_list')->name('show_zone_preopen_list');
    Route::get('show_zone_weekly_list/{zone_id}/{date}', 'Admin\ZoneWeeklyController@show_zone_weekly_list')->name('show_zone_weekly_list');
    Route::get('show_zone_daily_list/{zone_id}/{date}', 'Admin\ZoneDailyController@show_zone_daily_list')->name('show_zone_daily_list');

    Route::get('preclosApprove/{id}/{date}', 'Admin\ZonePreclosingController@approve')->name('preclosApprove');
    Route::get('preopenApprove/{id}/{date}', 'Admin\ZonePreopeningController@approve')->name('preopenApprove');
    Route::get('weeklyApprove/{id}/{date}', 'Admin\ZoneWeeklyController@approve')->name('weeklyApprove');
    Route::get('dailyApprove/{id}/', 'Admin\ZoneDailyController@approve')->name('dailyApprove');

    Route::resource('observations', 'Admin\ObservationController');
    Route::get('/search_observation/', 'Admin\ObservationController@search');
    Route::get('/add_observation/{ride_id}', 'Admin\ObservationController@add_observation')->name('add_observation');

    Route::get('observation-report', 'Admin\ReportsController@observationReport')->name('reports.observationReport');
    Route::get('show_observation-report', 'Admin\ReportsController@showObservationReport')->name('reports.showObservationReport');


    Route::get('/auto-refresh-page', 'Admin\AutoRefreshController')->name('auto-refresh-page');
    Route::resource('incident', 'Admin\GeneralIncidentController');
    Route::get('incident/{id}/approve', 'Admin\GeneralIncidentController@approve')->name('incident-approve-manager');
    Route::get('incident/{id}/approve_director', 'Admin\GeneralIncidentController@approve_director')->name('incident-approve-director');
    Route::get('search_incident', 'Admin\GeneralIncidentController@search');
    Route::Post('get-incident-images', 'Admin\GeneralIncidentController@getImage')->name('getIncidentImage');


    Route::resource('investigation', 'Admin\InvestigationController');
    Route::get('investigation/{id}/approve', 'Admin\InvestigationController@approve')->name('investigation-approve-manager');
    Route::get('investigation/{id}/approve_director', 'Admin\InvestigationController@approve_director')->name('investigation-approve-director');
    Route::get('/search_investigation/', 'Admin\InvestigationController@search');

    Route::resource('evacuations', 'Admin\EvacuationsController');
    Route::get('/search_evacuation/', 'Admin\EvacuationsController@search');
    Route::get('/evacuation_stoppages', 'Admin\EvacuationsController@evacuationStoppages')->name('evacuationStoppages');
    Route::get('/add_ride_evacuation/{id}', 'Admin\EvacuationsController@addEvacuationRide')->name('addEvacuationRide');
    Route::get('/add_park_evacuation/{id}', 'Admin\EvacuationsController@addEvacuationPark')->name('addEvacuationPark');
    Route::get('evacuation_report', 'Admin\EvacuationsController@reportEvacuation')->name('evacuation.report');

    Route::get('evaluation_operator_report', 'Admin\ReportsController@evaluationOperator')->name('evaluation.operator.report');
    Route::get('evaluation_supervisor_report', 'Admin\ReportsController@evaluationSupervisor')->name('evaluation.supervisor.report');

    Route::get('/get_zones', 'Admin\GeneralIncidentController@getZones')->name('getZones');
    Route::get('/get_rides', 'Admin\GeneralIncidentController@getRides')->name('getRides');

    Route::resource('statement', 'Admin\StatementController');
    Route::get('statement/{id}/approve', 'Admin\StatementController@approve');
    Route::get('add_statment/{id}', 'Admin\StatementController@addStatment')->name('addStatment');
    Route::get('show_statment/{id}', 'Admin\StatementController@showStatment')->name('showStatment');

    Route::get('incident-report', 'Admin\ReportsController@incidentReport')->name('reports.incidentReport');
    Route::get('show-incident-report', 'Admin\ReportsController@showIncidentReport')->name('reports.showIncidentReport');

    Route::get('ride_capacity', 'Admin\RideCapacityController@index')->name('rideCapacity');
    Route::post('ride_capacity_update', 'Admin\RideCapacityController@update')->name('rideCapacity.update');
    Route::post('change_capacity', 'Admin\RideCapacityController@changeCapacity')->name('changeCapacity');

    Route::get('ride_capacity_report', 'Admin\RideCapacityController@report')->name('rideCapacity.report');

    Route::resource('preopen_list', 'Admin\PreOpeneController');
    Route::get('show_preopen_list/{ride_id}/{park_time_id}', 'Admin\PreOpeneController@show_preopen_list')->name('show_preopen_list');

    Route::resource('preopen_list', 'Admin\PreCloseController');
    Route::get('show_preclose_list/{ride_id}/{park_time_id}', 'Admin\PreCloseController@show_preclose_list')->name('show_preclose_list');

    Route::resource('units', 'Admin\UnitController');
    Route::resource('units_properties', 'Admin\UnitPropertyController');

    Route::get('add_move_in/{id}', 'Admin\UnitPropertyController@addMovein')->name('addMovein');
    Route::get('add_intial_check/{id}', 'Admin\UnitPropertyController@addIntialCheck')->name('addIntialCheck');
    Route::get('add_move_out/{id}', 'Admin\UnitPropertyController@addMoveout')->name('addMoveout');

    Route::get('export-stoppage/{items}', 'Admin\ReportsController@exportStoppage')->name('export.stoppage');
    Route::get('export-cycles/{items}', 'Admin\ReportsController@exportCycles')->name('export.cycles');
    Route::get('export-queues/{items}', 'Admin\ReportsController@exportQueues')->name('export.queues');
    Route::get('inspecttio-list/{items}', 'Admin\ReportsController@exportInspection')->name('export.inspection');
    Route::get('audit/{items}', 'Admin\ReportsController@exportAudit')->name('export.audit');
    Route::get('operator/{items}', 'Admin\ReportsController@exportOperator')->name('export.operator');
    Route::get('attendance/{items}', 'Admin\ReportsController@exportAttendance')->name('export.attendance');
    Route::get('availability-report/{items}', 'Admin\AvailabilityReportController@export')->name('export.availability');
    Route::get('observation/report/{items}', 'Admin\ReportsController@exportObservation')->name('export.observation');
    Route::get('Health/report/{items}', 'Admin\ReportsController@exportHealth')->name('export.health');
    Route::get('capacity/report/{items}', 'Admin\ReportsController@exportCapacity')->name('export.capacity');
    Route::get('evacuation/report/{items}', 'Admin\ReportsController@exportEvacuation')->name('export.evacuation');
    Route::get('evaluation/operator/report/{items}', 'Admin\ReportsController@exportEvaluationOperator')->name('export.evaluation.operator');
    Route::get('evaluation/supervisor/report/{items}', 'Admin\ReportsController@exportEvaluationSupervisor')->name('export.evaluation.supervisor');

    Route::get('clear-flash-message', 'GeneralController@clearMessage')->name('clear.flash.message');

    Route::resource('daily-check', 'Admin\DailyCheckListQuestionController');
    Route::get('add_am_check', 'Admin\DailyCheckListQuestionController@addAmCheck')->name('addAmCheck');
    Route::get('edit_am_list', 'Admin\DailyCheckListQuestionController@editaAmList')->name('editAmList');
    Route::get('show_am_list/{id}', 'Admin\DailyCheckListQuestionController@showAmList')->name('showAmList');
    Route::get('am-search', 'Admin\DailyCheckListQuestionController@amSearch')->name('amSearch');

    Route::get('index_pm', 'Admin\DailyCheckListQuestionController@indexPm')->name('indexPm');
    Route::get('add_pm_check', 'Admin\DailyCheckListQuestionController@addPmCheck')->name('addPmCheck');
    Route::get('edit_pm_list', 'Admin\DailyCheckListQuestionController@editPmList')->name('editPmList');
    Route::get('show_pm_list/{id}', 'Admin\DailyCheckListQuestionController@showPmList')->name('showPmList');
    Route::get('pm-search', 'Admin\DailyCheckListQuestionController@pmSearch')->name('pmSearch');
    Route::Post('get-daily-images', 'Admin\DailyCheckListQuestionController@getImage')->name('getDailyImage');


    Route::resource('operator-evaluation', 'Admin\OperatorEvaluationController');
    Route::resource('supervisor-evaluation', 'Admin\SupervisorEvaluationController');
    Route::get('evaluations/{id}/approve', 'Admin\OperatorEvaluationController@approve');
    Route::get('search_evaluation/', 'Admin\SupervisorEvaluationController@search');
    Route::get('search_operator_evaluation/', 'Admin\OperatorEvaluationController@search');

    Route::resource('country', 'Admin\CountryController');

    Route::resource('training', 'Admin\TrainingController');
    Route::get('training_search/', 'Admin\TrainingController@search');
    Route::get('show-users-lists/{id}', 'Admin\TrainingController@showUsersLists')->name('showUsersLists');
    Route::get('show-user-checklist/{user_id}/{training_id}', 'Admin\TrainingController@showUserChecklist')->name('showUserChecklist');

    Route::get('show-user-actions/', 'Admin\GeneralController@showActions')->name('showActions');

app/Http/Controllers/Admin/OperatorEvaluationController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Requests\Dashboard\Accident\EvaluationRequest;
use App\Models\Evaluation;
use App\Models\User;
use App\Models\UserPark;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\Department;
use App\Models\Park;
use App\Models\Zone;
use App\Models\ParkTime;
use App\Models\EvaluationInfo;
use App\Models\Ride;
use Carbon\Carbon;
use Illuminate\Support\Facades\Storage;

class OperatorEvaluationController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

        if (auth()->user()->hasRole('Super Admin')) {
            $parks = Park::pluck('id')->all();
            $userparks = Park::pluck('name', 'id')->all();

        } else {
            $parks = auth()->user()->parks->pluck('id');
            $userparks = auth()->user()->parks->pluck('name', 'id');

        }
        $items = Evaluation::whereIn('park_id', $parks)->whereNotNull('operator_id')
            ->where('date', Carbon::now()->toDateString())
            ->get();

        return view('admin.Operator_evaluation.index', compact('items', 'userparks'));
    }

    public function search(Request $request)
    {
        
        $action = new \App\Models\Action();
        $action->user_id = auth()->User()->id;
        $action->action = 'search on  operator evaluation  ';
        $action->save(); 

        $items = [];

        $date = $request->query('date');
        $dateTo = $request->query('date_to');
        $park_id = $request->query('park_id');
        $operator_id = $request->query('operator_id');
        // dd($operator_id );
        if (auth()->user()->hasRole('Super Admin')) {
            $parks = Park::pluck('id')->all();
            $userparks = Park::pluck('name', 'id');
        } else {
            $parks = auth()->user()->parks->pluck('id');
            $userparks = auth()->user()->parks->pluck('name', 'id');
        }
        if ($park_id != null) {

            $items = Evaluation::where('park_id', $park_id)
                ->where('date', '>=', $date)->whereNotNull('operator_id');
            if ($dateTo) {
                $items = $items->where('date', '<=', $dateTo);
            }

            if ($operator_id != null) {
                $items->where('operator_id', $operator_id);
            }
            $items = $items->get();
            $users = UserPark::query()->where('park_id', $request->park_id)->
            whereHas('users.roles', function ($query) {
                return $query->whereIn('name', ['Operations/Operator', 'Breaker']); 
            })->pluck('user_id');
            $users = User::whereIn('id', $users)->pluck('name', 'id');
            return view('admin.Operator_evaluation.index', compact('items', 'userparks', 'users'));
        } else {
            $items = Evaluation::whereIn('park_id', $parks)->whereNotNull('operator_id')
                ->where('date', Carbon::now()->toDateString())
                ->get();
        }
        // $items=[];
        return view('admin.Operator_evaluation.index', compact('items', 'userparks'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
    }


    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(EvacuationRequest $request)
    {

    }


    public function edit($id)
    {
        $evaluation = Evaluation::find($id);
        $users = UserPark::query()->where('park_id', $evaluation->park_id)->
        whereHas('users.roles', function ($query) {
            return $query->whereIn('name', ['Operations/Operator', 'Breaker']); 
        })->pluck('user_id');
        $users = User::whereIn('id', $users)->pluck('name', 'id');
        $rides = Ride::where('park_id', $evaluation->park_id)->pluck('name', 'id');

        return view('admin.Operator_evaluation.edit', compact('evaluation', 'users', 'rides'));


    }

    public function show($id)
    {
        $list = Evaluation::find($id);
        $items = EvaluationInfo::where('evaluation_id', $id)->get();

        return view('admin.Operator_evaluation.show', compact('items', 'list', 'id'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $action = new \App\Models\Action();
        $action->user_id = auth()->User()->id;
        $action->action = 'update operator evaluation  ';
        $action->save(); 

        $validated = $request->validate([
            'comment' => 'required|array',
            'question_id' => 'required|array',
            'score' => 'required|array',
            'ride_id' => 'required|exists:rides,id',
            'operator_id' => 'required|exists:users,id',
            'remarks'=>'nullable'
        ]);
        $list = Evaluation::find($id);
        $totalScore = array_sum($validated['score']);
        $list->update(array_merge($validated, ['total_score' => $totalScore]));

        $list->lists->each->delete();
        foreach ($validated['question_id'] as $key => $question) {
            EvaluationInfo::query()->create([
                'evaluation_id' => $id,
                'evaluation_question_id' => $question,
                'comment' => $validated['comment'][$key] ?? null,
                'score' => $validated['score'][$key] ?? 0,
            ]);
        }
        alert()->success('Updated Successfully!');
        return redirect()->back();

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        
        $action = new \App\Models\Action();
        $action->user_id = auth()->User()->id;
        $action->action = 'delete operator evaluation  ';
        $action->save(); 

        $evaluation = Evaluation::find($id);
        if ($evaluation) {
            foreach ($evaluation->lists as $list) {
                $list->delete();
            }
            $evaluation->delete();
            alert()->success('Operator Evaluation  deleted successfully');
            return back();
        }
        alert()->error('Operator Evaluation  not found');
        return redirect()->route('admin.operator-evaluation.index');
    }

    protected function approve($id)
    {
        Evaluation::find($id)->update(['approve' => 'approved',
            'approved_at' => Carbon::now()->toDateTimeString(),
            'approve_by_id' => auth()->id()
        ]);
        alert()->success('Approved Successfully !');
        return redirect()->back();
    }

}

resources/views/admin/Operator_evaluation/ajax.blade.php
<div class="font-bold m-3 text-center">
    <span class="font-bold m-3 text-danger" >Total Count</span> :  @if (isset($items))
        {{$items->count()}}
    @else
        0
    @endif
</div>
@if(isset($items) && count($items) >0)
    <div class="form-group left row col-md-12">
        <a class="btn btn-info" href="{{ route('admin.export.evacuation',$items->pluck('id')) }}">Export File Csv</a>

    </div>
    <div id="datatable-buttons_wrapper" class="dataTables_wrapper dt-bootstrap4 no-footer">
        <div class="row">

            <div class="col-xs-12 ">
                <div class="col-xs-12 ">

                </div>
                <div class="col-xs-12">
                    <table id="datatable-buttons" class="table table-striped table-bordered dt-responsive nowrap">
                        <thead>
                        <tr role="row">
                            <th class="sorting_asc" tabindex="0" aria-controls="datatable-buttons" rowspan="1"
                                colspan="1" aria-sort="ascending">ID
                            </th>
                            <th class="sorting" tabindex="0" aria-controls="datatable-buttons" rowspan="1"
                                colspan="1">
                                Park
                            </th>
                            <th class="sorting" tabindex="0" aria-controls="datatable-buttons" rowspan="1"
                                colspan="1">
                                Ride
                            </th>
                            <th class="sorting" tabindex="0" aria-controls="datatable-buttons" rowspan="1"
                                colspan="1">
                                Total rider
                            </th>
                            <th class="sorting" tabindex="0" aria-controls="datatable-buttons" rowspan="1"
                                colspan="1">
                                First rider off
                            </th>
                            <th class="sorting" tabindex="0" aria-controls="datatable-buttons" rowspan="1"
                                colspan="1">
                                Last rider off
                            </th>

                            <th class="sorting" tabindex="0" aria-controls="datatable-buttons" rowspan="1"
                                colspan="1">
                                First aid
                            </th>
                            <th class="sorting" tabindex="0" aria-controls="datatable-buttons" rowspan="1"
                                colspan="1">
                                Evacuation details
                            </th>
                            <th class="sorting" tabindex="0" aria-controls="datatable-buttons" rowspan="1"
                                colspan="1">
                                Customer service gesture
                            </th>
                            <th class="sorting" tabindex="0" aria-controls="datatable-buttons" rowspan="1"
                                colspan="1">
                                Portal overview
                            </th>

                            <th class="sorting" tabindex="0" aria-controls="datatable-buttons" rowspan="1"
                                colspan="1">
                                Time Slot Date
                            </th>

                        </tr>
                        </thead>

                        <tbody>
                        @if (isset($items))
                            @foreach ($items as $item)
                                <tr role="row" class="odd" id="row-{{ $item->id }}">
                                    <td tabindex="0" class="sorting_1">{{ $item->id }}</td>
                                    <td>{{ $item->park?->name ?? '' }}</td>
                                    <td>{{ $item->ride?->name ?? '' }}</td>
                                    <td>{{ $item->total_rider }}</td>
                                    <td>{{  $item->first_rider_off }} </td>
                                    <td> {{ $item->last_rider_off }}</td>
                                    <td>{!!  $item->first_aid !!}</td>
                                    <td>{!! $item->evacuation_details  !!}</td>
                                    <td> {!! $item->customer_service_gesture   !!}</td>
                                    <td> {!! $item->portal_overview !!}</td>

                                    <td>{{ $item->submit_date }}</td>
                                </tr>
                            @endforeach
                        @endif

                        </tbody>
                    </table>


                </div>
            </div>
        </div>

    </div>
@endif

resources/views/admin/Operator_evaluation/index.blade.php
@extends('admin.layout.app')

@section('title')
   Operator Performance Evaluation
@endsection

@section('content')
    <div class="card-box">
        <form class="formSection" action="{{url('/search_operator_evaluation/')}}" method="GET">
            @csrf
            <div class="row">
                <div class='col-md-3'>
                    <div class="form-group">
                        <label for="last_name">Select Park</label>
                        {!! Form::select('park_id',$userparks,request()->park_id, array('class' => 'form-control park','id'=>'park','placeholder'=>'Choose Park', 'required' => 'required') ) !!}
                    </div>
                </div>
                <div class='col-md-3'>
                    <div class="form-group">
                        <label for="supervisor_id">Select Operator </label>
                        {!! Form::select('operator_id',$users?? [],null, array('class' => 'form-control supervisor','id'=>'supervisor','placeholder'=>'Choose Operator...')) !!}
                    </div>
                </div>

                <div class='col-md-3'>
                    <div class="form-group">
                        <label for="middle_name">Time Slot Date From </label>
                        {!! Form::date('date',request()->date ?? \Carbon\Carbon::now()->toDate(),['class'=>'form-control','id'=>'date', 'required' => 'required']) !!}
                    </div>
                </div>
                <div class='col-md-3'>
                    <div class="form-group">
                        <label for="middle_name">Time Slot Date To </label>
                        {!! Form::date('date_to',request()->date_to ?? \Carbon\Carbon::now()->toDate(),['class'=>'form-control','id'=>'date_to', 'required' => 'required']) !!}
                    </div>
                </div>

                <div class='col-md-12 mtButton ' style="text-align: center">
                    <div class="input-group-btn">
                        <button type="submit" class="btn btn-primary save_btn waves-effect">Show</button>
                    </div>
                </div>
            </div>
            {!!Form::close() !!}
            <br>
            <div id="datatable-buttons_wrapper" class="dataTables_wrapper dt-bootstrap4 no-footer">
                <div class="row">
                    <div class="col-sm-12">
                        <table id="datatable-buttons" class="table table-striped table-bordered dt-responsive nowrap">
                            <thead>
                            <tr role="row">
                                <th class="sorting_asc" tabindex="0" aria-controls="datatable-buttons" rowspan="1"
                                    colspan="1" aria-sort="ascending">ID
                                </th>
                                <th class="sorting" tabindex="0" aria-controls="datatable-buttons" rowspan="1"
                                    colspan="1">
                                    Date
                                </th>
                                <th class="sorting" tabindex="0" aria-controls="datatable-buttons" rowspan="1"
                                colspan="1">
                                Operator Name
                               </th>
                                <th class="sorting" tabindex="0" aria-controls="datatable-buttons" rowspan="1"
                                    colspan="1">
                                    Total Score
                                </th>
                                <th class="sorting" tabindex="0" aria-controls="datatable-buttons" rowspan="1"
                                    colspan="1">
                                    Ride
                                </th>
                                <th class="sorting" tabindex="0" aria-controls="datatable-buttons" rowspan="1"
                                    colspan="1">
                                    Park
                                </th>
                                <th class="sorting" tabindex="0" aria-controls="datatable-buttons" rowspan="1"
                                colspan="1">
                                   Status
                                </th>

                                <th class="sorting" tabindex="0" aria-controls="datatable-buttons" rowspan="1"
                                    colspan="1">
                                    Process
                                </th>
                            </tr>
                            </thead>

                            <tbody>

                            @foreach ($items as $item)
                                <tr role="row" class="odd" id="row-{{ $item->id }}">
                                    <td tabindex="0" class="sorting_1">{{ $item->id }}</td>
                                    <td>{{ $item->date}}</td>
                                    <td>{{ $item->operator?->name }}</td>
                                    <td>{{ $item->total_score }}</td>
                                    <td>{{ $item->ride?->name }}</td>
                                    <td>{{ $item->park?->name }}

                                        <td>
                                            @if ($item->approve == 'pending')
                                                <a href="{{ url('evaluations/' . $item->id . '/approve') }}"
                                                    class="btn btn-xs btn-danger"><i class="fa fa-check"></i> Approve</a>
                                            @else
                                                <span>Verified</span>
                                            @endif

                                    </td>
                                        <td>


                                       @if(auth()->user()->can('operator-evaluation-list'))

                                        <a href="{{ route('admin.operator-evaluation.show', $item->id) }}"
                                              class="btn btn-info">show</a>
                                                <a href="{{ route('admin.operator-evaluation.edit', $item->id) }}"
                                                   class="btn btn-info">edit</a>
                                      @endcan

                                            {!!Form::open( ['route' => ['admin.operator-evaluation.destroy',$item->id] ,'id'=>'delete-form'.$item->id, 'method' => 'Delete']) !!}
                                            {!!Form::close() !!}
                                            @if(auth()->user()->can('operator-evaluation-delete'))
                                            <a class="btn btn-danger" data-name=""
                                               data-url="{{ route('admin.operator-evaluation.destroy', $item) }}"
                                               onclick="delete_form(this)">
                                               Delete
                                            </a>
                                        @endcan
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
    </div>
@endsection
@section('footer')
    @include('admin.datatable.scripts')
@endsection
@push('scripts')

    <script type="text/javascript">
        $("#park").change(function () {
            $.ajax({
                url: "{{ route('admin.getOperatorByPark') }}?park_id=" + $(this).val(),
                method: 'GET',
                success: function (data) {
                    $('#supervisor').html(data.html);
                }
            });
        });

    </script>
@endpush